language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"

env:
  - SENCHA_CMD_VERSION="5.1.2.52"
  
before_script:
  - "wget http://cdn.sencha.com/cmd/$SENCHA_CMD_VERSION/SenchaCmd-$SENCHA_CMD_VERSION-linux-x64.run.zip"
  - "unzip -q SenchaCmd-$SENCHA_CMD_VERSION-linux-x64.run.zip"
  - "chmod +x SenchaCmd-$SENCHA_CMD_VERSION-linux-x64.run"
  - "./SenchaCmd-$SENCHA_CMD_VERSION-linux-x64.run --mode unattended"
  - "export PATH=~/bin/Sencha/Cmd/$SENCHA_CMD_VERSION/:$PATH"