language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  
before_script:
  - curl -o sencha-cmd.run.zip http://cdn.sencha.com/cmd/5.1.2.52/SenchaCmd-5.1.2.52-linux.run.zip
  - unzip -p sencha-cmd.run.zip > sencha-cmd.run
  - rm sencha-cmd.run.zip
  - chmod +x sencha-cmd.run
  - mkdir /tmp/sencha
  - ./sencha-cmd.run --mode unattended --prefix /tmp/sencha
  - rm sencha-cmd.run