language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  
before_script:
  - curl -o bundle/sencha-cmd.run.zip http://cdn.sencha.com/cmd/5.1.2.52/SenchaCmd-5.1.2.52-linux.run.zip
  - unzip -p bundle/sencha-cmd.run.zip > bundle/sencha-cmd.run
  - rm bundle/sencha-cmd.run.zip
  - chmod +x bundle/sencha-cmd.run
  - ./bundle/sencha-cmd.run --mode text
  - rm bundle/sencha-cmd.run