description: |
    Rapid Gui Application specification

extTheme: neptune

layout:
    - "personlist|personform"

views:
    -
        name: PersonGrid
        alias: personlist
        design:
            title: Persons
            type: grid
        dataContent:
            model: Person
            edit: true
            filter:
                -
                    alias: searchperson
                    type: text
                    field: all
                -
                    type: check
                    field: gender
                    items: [male, female]
        buttons: [clearFilter, reload]
    -
        name: PersonForm
        alias: personform
        design:
            title: Modify person data
            type: form
        dataContent:
            model: Person
        content:
            -
                name: Fields
                design:
                    type: auto

models:
    -
        name: Person
        proxy: http://localhost:3007/rest/persons
        fields: [id, contractCode, firstName, surName, gender, email, address, about]
        typedFields:
            -
                name: age
                type: int
            -
                name: employmentBeginDt
                type: date
                format: c
            -
                name: registered
                type: date
                format: c
useCases:
    -
        type: select
        on: personlist
        do:
            -
                cmd: load.personform
    -
        type: click
        on: personlist.#clearFilterBtn
        do:
            -
                cmd: clear.personlist
    -
        type: click
        on: personlist.checkbox
        do:
            -
                cmd: filter.personlist
    -
        type: click
        on: personlist.#reloadBtn
        do:
            -
                cmd: load.personlist
    -
        type: type
        on: personlist.#searchpersonTextfield
        do:
            -
                cmd: filter.personlist