description: |
    ExtJS application specification example

extTheme: neptune

layout:
    - "examplegrid|exampleform"
    - "exampleview"

views:
    -
        name: ExampleGrid
        alias: examplegrid
        layout: 
            title: Grid example
            type: grid
        dataContent:
            model: Person
    - 
        name: ExampleView
        alias: exampleview
        layout:
            title: Use case example
            type: form
        content:
            -
                name: ExampleField
                layout:
                    type: text
        buttons: [show]
    -
        name: ExampleForm
        alias: exampleform
        layout:
            title: Form example
            type: form
        dataContent:
            model: Person
        content:
            -
                name: Fields
                layout:
                    type: auto
        
models:
     -
        name: Person
        proxy: mock:10
        fields: [firstName, lastName, bio]
        typedFields:
            -
                name: age
                type: int
    
        
useCases:
    -
        type: click
        on: exampleview.#showBtn
        do:
            -
                cmd: show
                msg: Welcome in gui-tool\'s world!
    -
        type: select
        on: examplegrid
        do:
            -
                cmd: load.exampleform