description: |
    ExtJS application specification example

extTheme: neptune

layout:
    - "exampleview|examplegrid"

views:
    -
        name: ExampleGrid
        alias: examplegrid
        layout: 
            title: Grid example
            type: grid
        dataContent:
            model: Person
    - 
        name: ExampleView
        alias: exampleview
        layout:
            title: Use case example
            type: form
        content:
            -
                name: ExampleField
                layout:
                    type: text
        buttons: [show]
        
models:
     -
        name: Person
        proxy: mock:10
        fields: [firstName, lastName]
        typedFields:
            -
                name: age
                type: int
    
        
useCases:
    -
        type: click
        on: exampleview.#showBtn
        do:
            -
                cmd: show
                msg: Welcome in gui-tool\'s world!